# Generated by Django 3.0.3 on 2020-02-28 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('context', models.TextField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=15)),
                ('pw', models.CharField(max_length=15)),
                ('mname', models.CharField(max_length=30)),
                ('isFamily', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('mid', models.CharField(max_length=15)),
                ('mname', models.CharField(max_length=30)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Board')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Member'),
        ),
    ]
